from selenium import webdriver
import unittest

class NewVisitorTest(unittest.TestCase):

	def setUp(self):
		self.browser = webdriver.Firefox()

	def tearDown(self):
		self.browser.quit()

	def test_can_start_a_list_and_retrieve_it_later(self):
		# User hears about our new online app.
		# She first checks out the homepage
		self.browser.get('http://localhost:8000')

		# She notices the page title and header mention to-do lists
		self.assertIn('To-Do', self.browser.title)

		# She is invited to eneter a to-do item straight away
		inputbox = self.browser.find_element_by_id('id_new_item')
		self.assertEqual(
			inputbox.get_attribute('placeholder'),
			'Enter a to-do item'
		)

		# She enters 'Get groceries' into a text box
		inputbox.send_keys('Get groceries')

		# When she hits enter, the page updates and now lists:
		# "1:Get groceries" as an item in a to-do list
		inputbox.send_keys(Keys.ENTER)
		time.sleep(1)

		table = self.browser.find_element_by_id('id_list_table')
		rows = table.find_element_by_tag_name('tr')
		self.assertTrue(
			any(row.text == '1:Get groceries' for row in rows)
		)

		# There is still a text box inviting her to add another item
		# She enters "Pay gas bill"
		self.fail('Finish the test!')

		# The page updates again, and now has both items on her list

		# User wonders if the site will remember her To-do list.
		# She sees the unique URl generated by the site
		# She revists that URL to co check if her list is still there

		# She is done adding items for now

if __name__ == "__main__":
	unittest.main(warnings='ignore')