from selenium import webdriver
import unittest

class NewVisitorTest(unittest.TestCase):

	def setUp(self):
		self.browser = webdriver.Firefox()

	def tearDown(self):
		self.browser.quit()

	def test_can_start_a_list_and_retrieve_it_later(self):
		# User hears about our new online app.
		# She first checks out the homepage
		self.browser.get('http://localhost:8000')

		# She notices the page title and header mention to-do lists
		self.assertIn('To-Do', self.browser.title)
		self.fail('Finish the test!')


		# She is invited to eneter a to-do item straight away

		# She enters 'Get groceries' into a text box

		# When she hits enter, the page updates and now lists:
		# "1:Get groceries" as an item in a to-do list

		# There is still a text box inviting her to add another item
		# She enters "Pay gas bill"

		# The page updates again, and now has both items on her list

		# User wonders if the site will remember her To-do list.
		# She sees the unique URl generated by the site
		# She revists that URL to co check if her list is still there

		# She is done adding items for now

if __name__ == "__main__":
	unittest.main(warnings='ignore')